version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt -t .
  build:
    commands:
      - flask run
  artifacts:
    files:
      - '**/*'